# REFERENCE: Doxygen Configuration Manual
# https://www.doxygen.nl/manual/config.html
####################################################### GENERAL SETTINGS
set(DOXYGEN_EXAMPLE_PATH ${CMAKE_SOURCE_DIR}/tests)
set(DOXYGEN_QUIET NO)
set(DOXYGEN_RECURSIVE YES)
set(DOXYGEN_TAB_SIZE 2) # Tab size
#
set(DOXYGEN_USE_MDFILE_AS_MAINPAGE ${BQPP_DOCS_MAIN_MD})
set(DOXYGEN_EXCLUDE_PATTERNS "**/src/**/*.hpp")
######################################################### SCOPE SETTINGS
set(DOXYGEN_BUILTIN_STL_SUPPORT YES) # Support for std:: namespace
set(DOXYGEN_EXTRACT_ALL YES) # Everything
set(DOXYGEN_HIDE_UNDOC_RELATIONS NO)
set(DOXYGEN_JAVADOC_AUTOBRIEF YES) # brief is comment first line
set(DOXYGEN_TEMPLATE_RELATIONS YES) #
########################################################## HTML SETTINGS
set(DOXYGEN_CODE_FOLDING NO)
set(DOXYGEN_GENERATE_HTML YES)
set(DOXYGEN_HTML_DYNAMIC_SECTIONS NO)
set(DOXYGEN_SOURCE_BROWSER YES)
set(DOXYGEN_SOURCE_TOOLTIPS NO)
set(DOXYGEN_SEPARATE_MEMBER_PAGES NO)
set(DOXYGEN_STRIP_FROM_PATH ${CMAKE_SOURCE_DIR} ${CMAKE_BINARY_DIR}/include)
set(DOXYGEN_TIMESTAMP YES)
set(DOXYGEN_UML_LOOK NO)
############################################# C++ Preprocessing SETTINGS
set(DOXYGEN_ENABLE_PREPROCESSING YES)
set(DOXYGEN_EXPAND_ONLY_PREDEF NO)
set(DOXYGEN_INHERIT_DOCS YES)
set(DOXYGEN_MACRO_EXPANSION YES)
set(DOXYGEN_REFERENCED_BY_RELATION YES) #
set(DOXYGEN_REFERENCES_RELATION YES) #
set(DOXYGEN_REFERENCES_LINK_SOURCE YES) #
set(DOXYGEN_SKIP_FUNCTION_MACROS NO)
##############################################GRAPH GENERATING SETTINGS
set(DOXYGEN_DIRECTORY_GRAPH YES)
set(DOXYGEN_HAVE_DOT YES)
set(DOXYGEN_DOT_CLEANUP YES)
set(DOXYGEN_DOT_IMAGE_FORMAT png)
set(DOXYGEN_INTERACTIVE_SVG no)
set(DOXYGEN_DOT_MULTI_TARGETS YES)
set(DOXYGEN_DOT_NUM_THREADS 4)
############################################################### Graphs
set(DOXYGEN_CALL_GRAPH YES)
set(DOXYGEN_CALLER_GRAPH YES)
set(DOXYGEN_CLASS_GRAPH YES)
set(DOXYGEN_COLLABORATION_GRAPH YES)
set(DOXYGEN_DIRECTORY_GRAPH YES)
set(DOXYGEN_GROUP_GRAPHS YES)
set(DOXYGEN_INCLUDE_GRAPH YES)
set(DOXYGEN_INCLUDED_BY_GRAPH YES)


